# Generated by Django 3.1.5 on 2021-01-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDDiscount_ar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='The price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDiscription',
            field=models.TextField(verbose_name='Discribtion of product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDiscription_ar',
            field=models.TextField(verbose_name='Discribtion of product in arabic'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDName_ar',
            field=models.CharField(max_length=300, verbose_name='name of product in arabic'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='The price in arabic'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDSate',
            field=models.CharField(choices=[('new', 'new'), ('old', 'old')], max_length=20, verbose_name='state of product '),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDSate_ar',
            field=models.CharField(choices=[('جديد', 'جديد'), ('قديم', 'قديم')], max_length=20, verbose_name='state of product in arabic'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDType',
            field=models.CharField(choices=[('Carpets and meridians', 'Carpets and meridians'), ('the games', 'the games'), ('Electrical', 'Electrical'), ('Mobile phones', 'Mobile phones')], max_length=90, verbose_name='Type of product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDType_ar',
            field=models.CharField(choices=[('سجادات و زوالي', 'سجادات و زوالي'), ('الالعاب', 'الالعاب'), ('الكهربائيات', 'الكهربائيات'), ('الهواتف المحمولة', 'الهواتف المحمولة')], max_length=90, verbose_name='Type of product in arabic'),
        ),
    ]
