# Generated by Django 3.1.5 on 2021-01-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210115_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDDiscount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='The Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDiscount_ar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='The Discount in arabic'),
        ),
    ]
