# Generated by Django 3.1.5 on 2021-01-18 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20210115_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_add', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covernorate', models.CharField(choices=[('الأنبار', 'الأنبار'), ('ديالى', 'ديالى'), ('أربيل', 'أربيل'), ('بابل', 'بابل'), ('بغداد', 'بغداد'), ('البصرة', 'البصرة'), ('حلبجة', 'حلبجة'), ('دهوك', 'دهوك'), ('القادسية', 'القادسية'), ('ديالى', 'ديالى'), ('ذي قار', 'ذي قار'), ('السليمانية', '\tالسليمانية'), ('صلاح الدين', 'صلاح الدين'), ('كركوك', 'كركوك'), ('كربلاء', 'كربلاء'), ('المثنى', 'المثنى'), ('ميسان', 'ميسان'), ('النجف', 'النجف'), ('نينوى', 'نينوى'), ('واسط', 'واسط')], default='بغداد', max_length=30)),
                ('state', models.CharField(max_length=100)),
                ('phone_number1', models.CharField(max_length=11)),
                ('phone_number2', models.CharField(max_length=11)),
                ('date_add', models.DateTimeField(max_length=11)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.orderitem')),
            ],
        ),
    ]
