# Generated by Django 3.1.5 on 2021-01-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210119_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='order',
        ),
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.ManyToManyField(to='products.OrderItem'),
        ),
    ]
