# Generated by Django 3.1.5 on 2021-01-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210119_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.address'),
        ),
    ]
