# Generated by Django 3.1.5 on 2021-01-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210119_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='complate',
            field=models.BooleanField(default=False),
        ),
    ]
