# Generated by Django 3.1.5 on 2021-01-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_orderitem_complate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
