# Generated by Django 3.1.5 on 2021-01-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210120_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='complate',
            field=models.CharField(default='Cancel', max_length=20),
        ),
    ]
