# Generated by Django 3.1.5 on 2021-01-31 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210127_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_add',
            field=models.DateTimeField(default=datetime.date),
        ),
    ]
