# Generated by Django 3.1.5 on 2021-01-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210131_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='complate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
