# Generated by Django 3.1.5 on 2021-02-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210131_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='The Discount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='employee',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_type',
            field=models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('whatsapp', 'whatsapp'), ('directly', 'directly')], default='', max_length=9),
            preserve_default=False,
        ),
    ]
