# Generated by Django 3.1.5 on 2021-02-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210207_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
