# Generated by Django 3.1.5 on 2021-02-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20210212_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_number',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
